# Generated by Django 2.0 on 2017-12-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171219_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='eestec'),
            preserve_default=False,
        ),
    ]
